spring.application.name=enterprise-messages-server
spring.jackson.deserialization.fail-on-unknown-properties=true
server.port=8080

# Do?asná H2 in-memory databáze, jinak se to sesune ze závisloti na repo #Jirka //todo delete this
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update