spring.application.name=enterprise-messages-server
spring.jackson.deserialization.fail-on-unknown-properties=true
server.port=8080

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/nnpro}
spring.datasource.username=${DB_USERNAME:nnpro}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
