-- NNPRO / Enterprise Messages — PostgreSQL schema
-- One-time initialization only: execute on an EMPTY database/schema.
-- Deliberately omits DROP TABLE: existing data is never destroyed by this script.
-- Application services must validate membership, roles, DM server sizes and key-rotation authorization.
-- Symmetric/private keys are NOT stored here; only hashes, public keys and ciphertext.

BEGIN;

CREATE TABLE app_user
(
	id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	username varchar(100) NOT NULL,
	password_hash varchar(255) NOT NULL,
	display_name varchar(100) NULL,
	created_at timestamp with time zone NOT NULL   DEFAULT CURRENT_TIMESTAMP
)
;

CREATE TABLE channel
(
	id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	server_id bigint NOT NULL,
	name varchar(100) NOT NULL,
	created_at timestamp with time zone NOT NULL   DEFAULT CURRENT_TIMESTAMP
)
;

CREATE TABLE channel_key
(
	id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	channel_id bigint NOT NULL,
	version integer NOT NULL,
	created_at timestamp with time zone NOT NULL   DEFAULT CURRENT_TIMESTAMP,
	key_hash bytea NOT NULL,
	invalidated_at timestamp with time zone NULL
)
;

CREATE TABLE channel_member
(
	channel_id bigint NOT NULL,
	user_id bigint NOT NULL,
	joined_at timestamp with time zone NOT NULL   DEFAULT CURRENT_TIMESTAMP
)
;

CREATE TABLE message
(
	id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	channel_id bigint NOT NULL,
	sender_id bigint NOT NULL,
	ciphertext bytea NOT NULL,
	sent_at timestamp with time zone NOT NULL   DEFAULT CURRENT_TIMESTAMP,
	channel_key_id bigint NOT NULL
)
;

CREATE TABLE message_receipt
(
	message_id bigint NOT NULL,
	user_id bigint NOT NULL,
	delivered_at timestamp with time zone NULL,
	read_at timestamp with time zone NULL
)
;

CREATE TABLE message_server
(
	id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	name varchar(100) NOT NULL,
	created_at timestamp with time zone NOT NULL   DEFAULT CURRENT_TIMESTAMP,
	type varchar(20) NOT NULL
)
;

CREATE TABLE server_member
(
	server_id bigint NOT NULL,
	user_id bigint NOT NULL,
	role varchar(20) NOT NULL,
	joined_at timestamp with time zone NOT NULL   DEFAULT CURRENT_TIMESTAMP
)
;

CREATE TABLE user_key
(
	id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	user_id bigint NOT NULL,
	public_key text NOT NULL,
	created_at timestamp with time zone NOT NULL   DEFAULT CURRENT_TIMESTAMP,
	revoked_at timestamp with time zone NULL
)
;

ALTER TABLE app_user ADD CONSTRAINT "PK_app_user"
	PRIMARY KEY (id)
;

ALTER TABLE app_user
  ADD CONSTRAINT "UQ_app_user_username" UNIQUE (username)
;

ALTER TABLE channel ADD CONSTRAINT "PK_channel"
	PRIMARY KEY (id)
;

ALTER TABLE channel
  ADD CONSTRAINT "UQ_channel_server_name" UNIQUE (server_id,name)
;

ALTER TABLE channel_key ADD CONSTRAINT "PK_channel_key"
	PRIMARY KEY (id)
;

ALTER TABLE channel_key
  ADD CONSTRAINT "UQ_channel_key_version" UNIQUE (channel_id,version)
;

ALTER TABLE channel_key
  ADD CONSTRAINT "UQ_channel_key_id_channel" UNIQUE (id,channel_id)
;

ALTER TABLE channel_key ADD CONSTRAINT "CK_channel_key_version" CHECK (version > 0)
;

ALTER TABLE channel_member ADD CONSTRAINT "PK_channel_member"
	PRIMARY KEY (channel_id,user_id)
;

CREATE INDEX "IX_channel_member_user" ON channel_member (user_id ASC,channel_id ASC)
;

ALTER TABLE message ADD CONSTRAINT "PK_message"
	PRIMARY KEY (id)
;

CREATE INDEX "IX_message_channel_sent_at" ON message (channel_id ASC,sent_at ASC,id ASC)
;

ALTER TABLE message_receipt ADD CONSTRAINT "PK_message_receipt"
	PRIMARY KEY (message_id,user_id)
;

CREATE INDEX "IX_message_receipt_user_read" ON message_receipt (user_id ASC,read_at ASC)
;

ALTER TABLE message_server ADD CONSTRAINT "PK_message_server"
	PRIMARY KEY (id)
;

ALTER TABLE message_server ADD CONSTRAINT "CK_message_server_type" CHECK (type IN ('ORGANIZATION', 'DIRECT'))
;

ALTER TABLE server_member ADD CONSTRAINT "PK_server_member"
	PRIMARY KEY (server_id,user_id)
;

ALTER TABLE server_member ADD CONSTRAINT "CK_server_member_role" CHECK (role IN ('ADMINISTRATOR', 'MEMBER'))
;

CREATE INDEX "IX_server_member_user" ON server_member (user_id ASC,server_id ASC)
;

ALTER TABLE user_key ADD CONSTRAINT "PK_user_key"
	PRIMARY KEY (id)
;

CREATE INDEX "IX_user_key_user" ON user_key (user_id ASC)
;

ALTER TABLE channel ADD CONSTRAINT "FK_channel_server"
	FOREIGN KEY (server_id) REFERENCES message_server (id) ON DELETE NO ACTION ON UPDATE NO ACTION
;

ALTER TABLE channel_key ADD CONSTRAINT "FK_channel_key_channel"
	FOREIGN KEY (channel_id) REFERENCES channel (id) ON DELETE NO ACTION ON UPDATE NO ACTION
;

ALTER TABLE channel_member ADD CONSTRAINT "FK_channel_member_channel"
	FOREIGN KEY (channel_id) REFERENCES channel (id) ON DELETE CASCADE ON UPDATE NO ACTION
;

ALTER TABLE channel_member ADD CONSTRAINT "FK_channel_member_user"
	FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE NO ACTION ON UPDATE NO ACTION
;

ALTER TABLE message ADD CONSTRAINT "FK_message_channel"
	FOREIGN KEY (channel_id) REFERENCES channel (id) ON DELETE NO ACTION ON UPDATE NO ACTION
;

ALTER TABLE message ADD CONSTRAINT "FK_message_channel_key_channel"
	FOREIGN KEY (channel_key_id,channel_id) REFERENCES channel_key (id,channel_id) ON DELETE NO ACTION ON UPDATE NO ACTION
;

ALTER TABLE message ADD CONSTRAINT "FK_message_sender"
	FOREIGN KEY (sender_id) REFERENCES app_user (id) ON DELETE NO ACTION ON UPDATE NO ACTION
;

ALTER TABLE message_receipt ADD CONSTRAINT "FK_message_receipt_message"
	FOREIGN KEY (message_id) REFERENCES message (id) ON DELETE CASCADE ON UPDATE NO ACTION
;

ALTER TABLE message_receipt ADD CONSTRAINT "FK_message_receipt_user"
	FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE NO ACTION ON UPDATE NO ACTION
;

ALTER TABLE server_member ADD CONSTRAINT "FK_server_member_server"
	FOREIGN KEY (server_id) REFERENCES message_server (id) ON DELETE CASCADE ON UPDATE NO ACTION
;

ALTER TABLE server_member ADD CONSTRAINT "FK_server_member_user"
	FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE NO ACTION ON UPDATE NO ACTION
;

ALTER TABLE user_key ADD CONSTRAINT "FK_user_key_user"
	FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE NO ACTION ON UPDATE NO ACTION
;


-- PostgreSQL partial unique indexes not generated by Enterprise Architect.
-- Invalidate the previous channel key BEFORE inserting the new active key in one transaction.
CREATE UNIQUE INDEX "UQ_channel_key_active"
    ON channel_key (channel_id)
    WHERE invalidated_at IS NULL;

-- At most one active public key per user; revoked keys remain in history.
CREATE UNIQUE INDEX "UQ_user_key_active"
    ON user_key (user_id)
    WHERE revoked_at IS NULL;

COMMIT;
